language: python

python:
  - "2.7"

sudo: false

addons:
  postgresql: "9.3"
  apt:
    packages:
      - cmake
      - spatialite-bin
      - postgresql
      - postgis
      - python-qt4-dev
      - pyqt4-dev-tools
      - libproj-dev
        #- gdal-bin

install:
    - pip install pyspatialite

services: postgresql

before_script:
  - psql -c 'create database big_epanet_test_db;' -U postgres
  - psql -U postgres -c "create extension postgis"
  
script:
  - find / -name proj_api.h
  - cmake .
  - make
  - PYTHONPATH=$PWD ctest -V
